function t142_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t142__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom)+5;var textHeight=button.scrollHeight;if(buttonHeight<textHeight){button.classList.add('t142__submit-overflowed')}}
function t228__init(recid){var el=$('#rec'+recid);var mobile=el.find('.t228__mobile');var fixedBlock=mobile.css('position')==='fixed'&&mobile.css('display')==='block';setTimeout(function(){el.on('click','.t-menusub__target-link',function(){if(isMobile){if($(this).hasClass('t-menusub__target-link_active')){el.find('.t228').trigger('overflow')}else{el.find('.t228').trigger('nooverflow')}}});el.find('.t-menu__link-item:not(.t-menusub__target-link):not(.tooltipstered):not(.t794__tm-link)').on('click',function(){if($(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
if(fixedBlock){mobile.trigger('click')}});el.find('.t-menusub__link-item').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__right_buttons_but .t-btn').on('click',function(){if(fixedBlock){mobile.trigger('click')}});el.find('.t228__positionabsolute');el.find('.t228').on('overflow',function(){t228_checkOverflow(recid)});el.find('.t228').on('nooverflow',function(){t228_checkNoOverflow(recid)});el.find('.t228').on('showME601a',function(){el.find('.t966__menu-link').on('click',function(){if(fixedBlock){mobile.trigger('click')}})})},500)}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){var el=$('#rec'+recid);if($(window).width()>980){var t228_navLinks=el.find(".t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){setTimeout(function(){t228_catchScroll(t228_navLinks)},500)}}}
function t228_checkOverflow(recid){var el=$('#rec'+recid);var menu=el.find('.t228');var winHeight=$(window).height();if(menu.css('position')==='fixed'){menu.addClass('t228__overflow');menu[0].style.setProperty('height',winHeight-$('.t228__mobile_container').outerHeight(!0)+'px','important')}}
function t228_checkNoOverflow(recid){var el=$('#rec'+recid);var menu=el.find('.t228');var submenus=el.find('.t966__tooltip-menu_mobile');if(menu.css('position')==='fixed'){menu.removeClass('t228__overflow');menu[0].style.setProperty('height','auto')}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=[],t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=$(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref($(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=$(this)});t228_sections.sort(function(a,b){return b.offset().top-a.offset().top});t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var clickedSection=t228_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');$(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=$(window).scrollTop();var t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!==0&&t228_clickedSectionId===null&&t228_sections[t228_sections.length-1].offset().top>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
$(t228_sections).each(function(e){var t228_curSection=$(this),t228_id=t228_curSection.attr('id'),t228_sectionTop=t228_curSection.offset().top,t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=$(document).height()-$(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setWidth(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth();if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}
el.find(".t228__centerside").removeClass("t228__centerside_hidden")}
function t228_setBg(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{el.find(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");var topoffset=el.data('top-offset');if(topoffset&&parseInt(topoffset)>0){el.animate({"opacity":"1","top":topoffset+"px"},200,function(){})}else{el.animate({"opacity":"1","top":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}}})}}
function t228_changebgopacitymenu(recid){var el=$('#rec'+recid);if($(window).width()>980){el.find(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var el=$("#rec"+recid);var menu=el.find(".t228");var burger=el.find(".t228__mobile");burger.on('click',function(e){menu.fadeToggle(300);burger.toggleClass("t228_opened")});$(window).bind('resize',t_throttle(function(){if($(window).width()>980){menu.fadeIn(0)}}))}
function t480_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;t480_setHeight(recId);if(window.isMobile){$(window).on('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}else{window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t480_setHeight(recId)}))}
$(container).on('displayChanged',function(){t480_setHeight(recId)})}
function t480_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var sizer=rec.querySelector('.t480__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var imgWrapper=rec.querySelector('.t480__blockimg');var imgWidth=imgWrapper.clientWidth;var sizerAttrStyle=sizer.getAttribute('style');var windowHeight=window.innerHeight;if(window.isMobile&&sizerAttrStyle&&sizerAttrStyle.indexOf('vh')!==-1){sizerHeight=document.documentElement.clientHeight*parseFloat(windowHeight/sizerHeight);imgWrapper.style.height=(imgWidth/ratio)+'px'}else if(sizerHeight!=windowHeight){imgWrapper.style.height=(imgWidth/ratio)+'px'}}
function t509_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t509');if(!container)return;var images=rec.querySelectorAll('.t509__blockimg');for(var i=0;i<images.length;i++){var image=images[i];var imageWidth=image.getAttribute('data-image-width');var imageHeight=image.getAttribute('data-image-height');if(imageHeight.indexOf('vh')===-1){imageHeight=parseInt(imageHeight,10)}else{imageHeight=parseInt(imageHeight,10)/100*window.innerHeight}
var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;image.style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>960){var desktopImage=rec.querySelector('.t509__desktopimg');if(desktopImage){var height=desktopImage.clientHeight;var textWrappers=rec.querySelectorAll('.t509__textwrapper');for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=height+'px'}}}}
function t911_init(recid){t911_checkPhoneNumber(recid)}
function t911_checkPhoneNumber(recid){var el=$('#rec'+recid);var whatsapp=el.find('.t911__whatsapp').attr('data-messenger-whatsapp');var telegram=el.find('.t911__telegram').attr('data-messenger-telegram');var telegramLink=el.find('.t911__telegram_link').attr('data-messenger-telegram-link');var vk=el.find('.t911__vk').attr('data-messenger-vk');var skype=el.find('.t911__skype').attr('data-messenger-skype');var skypeChat=el.find('.t911__skype_chat').attr('data-messenger-skype-chat');var mail=el.find('.t911__mail').attr('data-messenger-mail');var viber=el.find('.t911__viber').attr('data-messenger-viber');var fb=el.find('.t911__fb').attr('data-messenger-fb');var phone=el.find('.t911__phone').attr('data-messenger-phone');if(typeof telegramLink!='undefined'){if(telegramLink.search(/http/i)!==-1){el.find('.t911__telegram_link').attr('href',telegramLink)}else{if(telegramLink.search(/tg/i)!==-1){el.find('.t911__telegram_link').attr('href',telegramLink)}else{el.find('.t911__telegram_link').attr('href','https://'+telegramLink)}}}
if(typeof whatsapp!='undefined'){el.find('.t911__whatsapp').attr('href','https://api.whatsapp.com/send?phone='+whatsapp.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t911__telegram').attr('href','https://t.me/'+telegram);el.find('.t911__vk').attr('href','https://vk.me/'+vk);if(typeof skype!='undefined'){el.find('.t911__skype').attr('href','skype:'+skype.replace(/[+?^${}()|[\]\\\s]/g,'')+'?call')}
if(typeof skypeChat!='undefined'){el.find('.t911__skype_chat').attr('href','skype:'+skypeChat.replace(/[+?^${}()|[\]\\\s]/g,'')+'?chat')}
if(typeof viber!='undefined'){el.find('.t911__viber').attr('href','viber://chat?number=%2B'+viber.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t911__mail').attr('href','mailto:'+mail);el.find('.t911__fb').attr('href','https://m.me/'+fb);if(typeof phone!='undefined'){el.find('.t911__phone').attr('href','tel:+'+phone.replace(/[+?^${}()|[\]\\\s]/g,''))}}
function t966_init(recid){var hook=$('#rec'+recid+' .t966').attr('data-tooltip-hook');if(typeof hook==='undefined'||hook===''){return}
var hookLinks=$('a[href=\''+hook+'\'][data-submenu-disallowed!="yes"]');hookLinks.addClass('t966__tm-link');hookLinks.attr('data-tooltip-menu-id',recid);var parentMenu=hookLinks.closest('[data-menu]');var tooltipMenu=$('#rec'+recid+' .t966__tooltip-menu');tooltipMenu.attr('data-pos-fixed','no');if(parentMenu.length&&parentMenu.css('position')=='fixed'){tooltipMenu.attr('data-pos-fixed','yes')}
t966_addArrow(recid,hookLinks);t966_setUpMenu(recid,hookLinks);t966_highlight()}
function t966_divideMenu(recid,rows){if(rows===''){rows=1}
var el=$('#rec'+recid).find('.t966');var menu=$('#rec'+recid+' .t966__menu-item-wrapper');var list=$('#rec'+recid+' .t966__menu-list');var count=menu.length;var max=Math.ceil(count/rows);if($(window).width()<980&&el.attr('data-sort-mobile')=="yes"){return}
var rowclass='';switch(rows){case '1':rowclass='t966__menu-list-row_100';break;case '2':rowclass='t966__menu-list-row_50';break;case '3':rowclass='t966__menu-list-row_33';break;case '4':rowclass='t966__menu-list-row_25';break}
for(var i=0;i<max;i++){list.append('<div class="t966__menu-list-row '+rowclass+'"></div>')}
var listRows=list.find('.t966__menu-list-row');menu.each(function(index){$(this).appendTo(listRows[index%max])});var curMode=$('.t-records').attr('data-tilda-mode');if(curMode==='edit'){$('.t966__tooltip-menu').css('display','block')}}
function t966_setUpMenu(recid,hookLinks){var submenu=$('#rec'+recid+' .t966__tooltip-menu');var content=submenu.find('t966__content');var vIndent=$('#rec'+recid+' .t966').attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on('mouseover',function(){if(!window.isMobile||$(window).width()>=980){if($(this).hasClass('t966__tooltip-menu')&&!$(this).hasClass('t966__tooltip-menu_show')){return}
clearTimeout(timer);if($(this).hasClass('t966__tooltip-menu')&&submenu.hasClass('t966__tooltip-menu_show')){return}
var curAnchor=$(this);t966_showSubmenu(recid,curAnchor,submenu,vIndent)}});hookLinks.add(submenu).on('mouseout',function(event){if(!window.isMobile||$(window).width()>=980){timer=setTimeout(function(){t966_hideSubmenu(recid,submenu)},300)}});$(document).on('click',function(e){if(submenu.attr('data-mobiletooltip')==='yes'){if(!submenu.is(e.target)&&submenu.has(e.target).length===0&&(!$(e.target).is(hookLinks)&&!$(e.target).is(hookLinks.children()))){t966_hideSubmenu(recid,submenu)}}});hookLinks.on('click',function(e){e.preventDefault();if(window.isMobile&&$(window).width()<980){if($(this).hasClass('t-menu__link-item')){if(submenu.hasClass('t966__tooltip-menu_show')||$(this).next().hasClass('t966__tooltip-menu_mobile')){var submenu_mobile=$(this).next();t966_hideSubmenu(recid,submenu_mobile)}else{var curAnchor=$(this);var submenu_mobile=submenu.clone();submenu_mobile.addClass('t966__tooltip-menu_mobile');t966_showSubmenu(recid,curAnchor,submenu_mobile,vIndent)}}else{if($(this).hasClass('t966__tooltip-menu')&&!$(this).hasClass('t966__tooltip-menu_show')){return}
clearTimeout(timer);if($(this).hasClass('t966__tooltip-menu')&&submenu.hasClass('t966__tooltip-menu_show')){return}
var curAnchor=$(this);t966_showSubmenu(recid,curAnchor,submenu,vIndent);var tooltips=$('#rec'+recid+' .t966__tooltip-menu[data-mobiletootlip="yes"]');if(tooltips.length!==0){t966_hideSubmenu(recid,tooltips)}}}});$(window).bind('scroll',t_throttle(function(){content.hover(function(){},function(){if(submenu.hasClass('t966__tooltip-menu_show')||hookLinks.filter('.t966__tm-link_active').next().hasClass('t966__tooltip-menu_mobile')){var submenu_mobile=hookLinks.filter('.t966__tm-link_active').next();t966_hideSubmenu(recid,submenu_mobile)}})},300));$(window).bind('resize',t_throttle(function(){if(!window.isMobile||$(window).width()>=980){t966_hideSubmenu(recid,$('.t966__tooltip-menu_mobile'))}},300));$('.t966__tooltip-menu a[href*="#"]').click(function(){t966_hideSubmenu(recid,submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu');$('.t966__tooltip-menu a[href*="#"]').removeClass('t-active');$(this).addClass('t-active')})}
function t966_showSubmenu(recid,curAnchor,submenu,vIndent){if(window.isMobile&&$(window).width()<980&&curAnchor.hasClass('t-menu__link-item')){submenu.insertAfter(curAnchor);$('.t966__tooltip-menu a[href*="#"]').click(function(){t966_hideSubmenu(recid,submenu);$('.t966__tooltip-menu a[href*="#"]').removeClass('t-active');$(this).addClass('t-active')});submenu.parents('.t228').trigger('overflow').trigger('showME601a');submenu.css({'position':'static','opacity':'1'});if(submenu.closest('.t280').length>0||submenu.closest('.t450').length>0||submenu.closest('.t451').length>0){submenu.show()}else{submenu.slideDown()}
submenu.addClass('t966__tooltip-menu_show');curAnchor.addClass('t966__tm-link_active');if(window.lazy=='y'){t_lazyload_update()}
return}
if(!curAnchor.hasClass('t-menu__link-item')){submenu.find('.t966__tooltip-menu-corner-border').css('opacity','1');submenu.find('.t966__tooltip-menu-corner').css('opacity','1');if(window.isMobile&&$(window).width()<980){submenu.attr('data-mobiletooltip','yes')}}
var isFirefox=navigator.userAgent.search("Firefox")!==-1;var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorTop=curAnchor.offset().top;var anchorLeft=curAnchor.offset().left;var corner=submenu.find('.t966__tooltip-menu-corner');var cornerBorder=submenu.find('.t966__tooltip-menu-corner-border');var cornerLeft;var menuFixed=submenu.attr('data-pos-fixed');var parentZeroMenu=curAnchor.closest('.t396__artboard');var menuWindowMargin=10;var arrowHeight=10;var vIndentDefault=25;if(typeof vIndent!='undefined'&&vIndent!=''){vIndent=vIndent.replace('px','')*1;vIndent=vIndent+arrowHeight}else{vIndent=vIndentDefault}
var posy;if(menuFixed=='yes'){posy=(curAnchor.offset().top-scrollTop)+anchorHeight+vIndent;submenu.css('position','fixed')}else{posy=curAnchor.offset().top+anchorHeight+vIndent}
var posx=anchorLeft;if(parentZeroMenu.hasClass('t396__artboard_scale')&&window.tn_scale_factor){posx=isFirefox?posx:posx*window.tn_scale_factor;anchorLeft=isFirefox?anchorLeft:anchorLeft*window.tn_scale_factor;anchorWidth=anchorWidth*window.tn_scale_factor}
if(posy+submenuHeight>scrollTop+winHeight&&posy>=submenuHeight&&posy-scrollTop>submenuHeight){posy=Math.max(posy-submenuHeight-anchorHeight-vIndent*2,scrollTop);corner.removeClass('t966__tooltip-menu-corner_bottom').addClass('t966__tooltip-menu-corner_top');cornerBorder.removeClass('t966__tooltip-menu-corner-border_bottom').addClass('t966__tooltip-menu-corner-border_top')}else{corner.removeClass('t966__tooltip-menu-corner_top').addClass('t966__tooltip-menu-corner_bottom');cornerBorder.removeClass('t966__tooltip-menu-corner-border_top').addClass('t966__tooltip-menu-corner-border_bottom')}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=menuWindowMargin}}else{posx=winWidth-submenuWidth-menuWindowMargin}
if(Math.ceil(submenuWidth)+menuWindowMargin*2>winWidth){posx=menuWindowMargin;submenu.css('width',winWidth-menuWindowMargin*2)}
submenu.css({'left':posx,'top':posy});submenu[0].offsetHeight;submenu.fadeIn(0);submenu.addClass('t966__tooltip-menu_show');curAnchor.addClass('t966__tm-link_active');cornerLeft=anchorLeft+Math.floor(anchorWidth/2)-posx-(arrowHeight/2);corner.css('left',cornerLeft);cornerBorder.css('left',cornerLeft);if(submenu.offset().top-$(window).scrollTop()+submenu.height()>$(window).height()&&submenu.attr('data-mobiletooltip')!=='yes'){var content=submenu.find('.t966__content');var contentPadding=parseInt(content.css('paddingBottom'),10);var paddingWindow=40;var height=$(window).height()-posy-contentPadding-paddingWindow-arrowHeight;content.css({"overflow-y":"scroll","height":height})}
if(window.lazy=='y'){t_lazyload_update()}}
function t966_hideSubmenu(recid,submenu){if(submenu.attr('data-mobiletooltip')==='yes'){submenu.attr('data-mobiletooltip','')}
if(submenu.hasClass('t966__tooltip-menu_mobile')){if(submenu.closest('.t280').length>0||submenu.closest('.t450').length>0||submenu.closest('.t451').length>0){submenu.hide(0,function(){submenu.remove()})}else{submenu.slideUp("normal",function(){submenu.parents('.t228').trigger('nooverflow');submenu.remove()})}
$('.t966__tm-link_active').removeClass('t966__tm-link_active');return}else{var content=submenu.find('.t966__content');submenu.css({"display":"","left":"","top":"","width":""});content.css({"overflow-y":"","height":""});submenu.removeClass('t966__tooltip-menu_show')}
$('.t966__tm-link_active').removeClass('t966__tm-link_active')}
function t966_addArrow(recid,hookLinks){var arrow=$('#rec'+recid+' .t966').attr('data-add-arrow');if(typeof arrow=='undefined'||arrow==''){return}
hookLinks.each(function(i,el){$(el).append('<div class="t966__arrow"></div>')})}
function t966_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$('a[href=\''+url+'\'] .t966__menu-item-title').addClass('t-active');$('a[href=\''+url+'/\'] .t966__menu-item-title').addClass('t-active');$('a[href=\''+pathname+'\'] .t966__menu-item-title').addClass('t-active');$('a[href=\'/'+pathname+'\'] .t966__menu-item-title').addClass('t-active');$('a[href=\''+pathname+'/\'] .t966__menu-item-title').addClass('t-active');$('a[href=\'/'+pathname+'/\'] .t966__menu-item-title').addClass('t-active');if(hash){$('a[href=\''+hash+'\'] .t966__menu-item-title').addClass('t-active')}}
function t986_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var openBtn=rec.querySelector('.t986__playbutton');var closeBg=rec.querySelector('.t986__closevideo-bg');if(openBtn){openBtn.addEventListener('click',function(e){e.preventDefault();t986_showVideo(recid)})}
if(closeBg){closeBg.addEventListener('click',function(){t986_hideVideo(recid)})}}
function t986_showVideo(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoContainer=rec.querySelector('.t986__video-container');var videoCover=rec.querySelector('.t986__cover');var videoCarrier=rec.querySelector('.t986__video-carier');var youTubeID=videoContainer?videoContainer.getAttribute('data-content-popup-video-url-youtube'):'';var videoURL=youTubeID?'https://www.youtube.com/embed/'+youTubeID:'';document.body.classList.add('t986__overflow');if(videoCover)videoCover.classList.add('t986__hidden');if(videoContainer)videoContainer.classList.remove('t986__hidden');if(videoCarrier){var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+recid;iframe.classList.add('t986__iframe');iframe.width='100%';iframe.height='540';iframe.src=videoURL+'?rel=0&autoplay=1';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');var closeLink=document.createElement('a');closeLink.classList.add('t986__close-link');var closeLinkContent=document.createElement('div');closeLinkContent.classList.add('t986__close');closeLink.insertAdjacentElement('beforeend',closeLinkContent);videoCarrier.innerHTML='';videoCarrier.insertAdjacentElement('beforeend',iframe);videoCarrier.insertAdjacentElement('beforeend',closeLink)}
document.addEventListener('click',function(e){if(e.target.closest('.t986__close-link')){t986_hideVideo(recid)}})}
function t986_hideVideo(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoContainer=rec.querySelector('.t986__video-container');var videoCover=rec.querySelector('.t986__cover');var videoCarrier=rec.querySelector('.t986__video-carier');document.body.classList.remove('t986__overflow');if(videoCover)videoCover.classList.remove('t986__hidden');if(videoContainer)videoContainer.classList.add('t986__hidden');if(videoCarrier)videoCarrier.innerHTML='<div class="t986__video-bg2"></div>'}